package com.onepay.onepaygo.api.response

data class TransactionDetailsResponse(val Transaction: Transaction, val Amount: String, val CaptureAmount: String, val SettlementAmount: String, val ApprovedAmount: String, val TransactionType: String, val DateTime: String, val CardNumber: String)

data class Transaction(
    val AccountNumberLast4: String,
    val AuthNtwkName: String,
    val InvoiceNumber: String?,
    val Id: Int,
    val TerminalId: String?,
    val TransactionAmount: String,
    val SettlementAmount: String,
    val Method: String,
    val TransactionType: Int,
    val Nonce: String?,
    val ReferenceTransactionId: Int,
    val RelatedTransactionID: Int?,
    val ClientIP: String,
    val SourceApplication: String,
    val TransactionNotes: String,
    val ExpirationDate: String,
    val FirstName: String?,
    val LastName: String,
    val Street1: String?,
    val Street2: String,
    val City: String,
    val State: String,
    val Country: String,
    val Zip: String,
    val PhoneNumber: String?,
    val CustomerId: String,
    val Email: String,
    val ResultCode: String,
    val ResultSubCode: String,
    val ResultText: String?,
    val TransactionDatetime: String,
    val MerchantTransactionDateTime: String,
    val BatchId: Int,
    val SettledStatus: Int?,
    val ProcessorId: Int,
    val AVSResultCode: String,
    val CVVResultCode: String,
    val AuthID: String,
    val AuthNtwkID: String,
    val ProcessorACI: String?,
    val ProcessorCardLevelResultCode: String,
    val ApprovedAmount: String,
    val SourceUser: String,
    val AccountType: String,
    val Token: String,
    val POSEntryModeDesc : String,
    val SettlementDate : String,
    val AuthCode : String,
    val IndustryCode : String,
    val L2Id : Int,
    val L3Id : Int,
    val Test : Int,

    val EmailReceipt : String,
    val CardCaptCap : String,
    val ProcessorTranID : String,
    val product_id : String,
    val card_class : String,
    val detailcard_indicator : String,
    val prepaid_indicator : String,
    val debitnetwork_indicator : String,
    val MerchantTerminalID : Int,
    val Company : String,
    val SourceIP: String,
    val ProductDescription: String,
    val TaxAmount : Double,
    val TaxIndicator : Int,
    val VatALtTaxAmount : Double,
    val DiscountAmount : Double,
    val DestPostalCode : String,
    val ItemSeqNum : String,
    val ItemCode : String,
    val ItemDescription : String,
    val ShipFromPostalCode : String,
    val DestCountryCode : String,
    val VatALtTaxRate : Double,
    val Lvl3ItemQuantity : Double,
    val Lvl3UnitCost : Double,
    val Lvl3UnitofMeasure : String,
    val Lvl3DiscountAmount : Double,
    val Lvl3VatAltTaxAmount : Double,
    val Lvl3VatAltTaxRate : Double,
    val Lvl3ExtendedItemAmount : Double,
    val Lvl3ProductCode : String,
    val Lvl3LineItemTotal : Double,
    val Lvl3TaxIndicator : Int,
    val Lvl3TaxRate : Double,
    val Lvl3ProductDescriptor : String,
    val Lvl3TaxAmount : Double,
    val Lvl3TaxTypeIdentifier : String,
    val UserDefined20 : String,
    val UserDefined19 : String,
    val UserDefined18 : String,
    val UserDefined17 : String,
    val UserDefined16 : String,
    val UserDefined15 : String,
    val UserDefined14 : String,
    val UserDefined13 : String,
    val UserDefined12 : String,
    val UserDefined10 : String,
    val UserDefined11 : String,
    val UserDefined9 : String,
    val UserDefined8 : String,
    val UserDefined7 : String,
    val UserDefined6 : String,
    val UserDefined5 : String,
    val UserDefined4 : String,
    val UserDefined3 : String,
    val UserDefined2 : String,
    val UserDefined1 : String
)
