package com.onepay.onepaygo.api.response

data class TransactionDetailsResponse(val Transaction: Transaction, val Amount: String, val TransactionType: String, val DateTime: String, val CardNumber: String)

data class Transaction(
    val AccountNumberLast4: String,
    val AuthNtwkName: String,
    val InvoiceNumber: String?,
    val Id: Int,
    val TerminalId: String?,
    val TransactionAmount: Double,
    val SettlementAmount: Double,
    val Method: String,
    val TransactionType: Int,
    val Nonce: String?,
    val ReferenceTransactionId: Int,
    val RelatedTransactionID: Int?,
    val ClientIP: String,
    val SourceApplication: String,
    val TransactionNotes: String,
    val ExpirationDate: String,
    val FirstName: String?,
    val LastName: String,
    val Street1: String?,
    val Street2: String,
    val City: String,
    val State: String,
    val Zip: String,
    val PhoneNumber: String?,
    val CustomerId: String,
    val Email: String,
    val ResultCode: String,
    val ResultSubCode: String,
    val ResultText: String?,
    val TransactionDatetime: String,
    val MerchantTransactionDateTime: String,
    val BatchId: Int,
    val SettledStatus: Int,
    val ProcessorId: Int,
    val AVSResultCode: String,
    val CVVResultCode: String,
    val AuthID: String,
    val AuthNtwkID: String,
    val ProcessorACI: String?,
    val ProcessorCardLevelResultCode: String,
    val ApprovedAmount: String,
    val SourceUser: String,
    val SourceIP: String
)