package com.onepay.miura.common

class PreferencesKeys {

    companion object{
        val SHARED_PREFS = "onePayGo"
        const val userName = "username"
        const val emailConfirmed = "emailConfirmed"
        const val SaveLogin = "savelogin"
        const val access_token = "access_token"
        const val token_type = "token_type"
        const val refresh_token = "refresh_token"
        const val GatewayId = "GatewayId"
        const val UserId = "UserId"
        const val UserType = "UserType"
        const val terminalId = "terminalId"
        const val GatewayterminalId = "GatewayterminalId"
        const val getFromAPiId = "getFromAPiId"
        const val AuthxUserId = "AuthxUserId"
        const val ksn = "ksn"
        const val maskedpan = "maskedpan"
        const val track1 = "track1"
        const val track2 = "track2"
        const val track3 = "track3"
        const val transactionID = "transactionID"
        const val deviceCode = "deviceCode"
        const val deviceId = "deviceId"
        const val base64Signature = "base64Signature"
        const val bluetoothStatus = "bluetoothStatus"
        const val locationStatus = "locationStatus"
        const val deviceStatus = "deviceStatus"
        const val deviceTdynamo = "deviceTdynamo"
        const val bluetoothAddress = "bluetoothAddress"
        const val devicebbpos = "devicebbpos"
        const val paymentStatus = "paymentStatus"
        const val URL = "URL"
        const val PaymentURL = "PaymentURL"
        const val flowValue = "flowValue"
        const val terminalValues = "terminalValues"
        const val tickPos = "tickPos"
        const val tickPosdevice = "tickPosdevice"
        const val hash = "hash"
        const val retail = "retail"
        const val moto = "moto"
        const val arqc = "arqc"
        const val pos = "pos"
        const val entryMode = "entry_mode"
        const val serviceCode = "serviceCode"
        const val LogFilePath = "logfilepath"
        const val callBack = "call_back"
        const val email = "email"

    }
}